docs: Adding documentation
nextcord/nextcord-ext-menus pull request #20
Opened 2021-11-02 13:19 UTC by DenverCoder1

2021-11-02 13:44 UTC, VincentRPS requested changes

2021-11-02 13:44 UTC, VincentRPS commented on docs/conf.py
> +html_theme = "sphinx_rtd_theme"
I would suggest to use the Sphinx book theme imo it looks better

2021-11-02 13:44 UTC, VincentRPS commented on docs/ext/menus/api.rst
> +
```suggestion

.. _ext_menus_api:

```

2021-11-02 13:44 UTC, VincentRPS commented on docs/ext/menus/button_menus.rst
> +
```suggestion

.. _ext_menus_button_menus:
```

2021-11-02 13:44 UTC, VincentRPS commented on docs/ext/menus/reaction_menus.rst
> +
```suggestion

.. _ext_menus_reaction_menus:
```

2021-11-02 20:31 UTC, parker02311 commented
Documentation is a great idea, I was actually gonna work on this today. This will make understanding menus much easier for newer users.

2021-11-03 22:30 UTC, parker02311 commented
LGTM

2021-11-03 23:57 UTC, VincentRPS requested changes
Fix the copyright year

2021-11-03 23:57 UTC, VincentRPS commented on docs/conf.py
> +copyright = "2021-present, Nextcord. 2015-2020, Danny (Rapptz)"
Fixed incorrect copyright years
```suggestion
copyright = "2021-present, Nextcord. 2020-2021, Danny (Rapptz)"
```

2021-11-10 19:35 UTC, parker02311 approved these changes
LGTM
Should push ASAP for those that need help understanding menus

2021-11-10 20:02 UTC, merged